use super::{BindingAction, KeyBindingConfig, KeyBindingsConfig};

pub(super) fn default_keybindings_config() -> KeyBindingsConfig {
    KeyBindingsConfig {
        global: vec![
            KeyBindingConfig::new(BindingAction::Quit, "q"),
            KeyBindingConfig::new(BindingAction::Refresh, "r"),
            KeyBindingConfig::new(BindingAction::Confirm, "<enter>"),
            KeyBindingConfig::new(BindingAction::GoHome, "gh"),
            KeyBindingConfig::new(BindingAction::OpenBoards, "b"),
            KeyBindingConfig::new(BindingAction::OpenInBrowser, "o"),
            KeyBindingConfig::new(BindingAction::OpenSettings, ","),
        ],
        home: vec![
            KeyBindingConfig::new(BindingAction::Quit, "q"),
            KeyBindingConfig::new(BindingAction::OpenCurrentSprint, "c"),
            KeyBindingConfig::new(BindingAction::OpenMyIssues, "i"),
            KeyBindingConfig::new(BindingAction::OpenSearchIssues, "s"),
            KeyBindingConfig::new(BindingAction::OpenNewIssue, "n"),
            KeyBindingConfig::new(BindingAction::OpenBoards, "b"),
            KeyBindingConfig::new(BindingAction::OpenSyncStatus, "t"),
            KeyBindingConfig::new(BindingAction::OpenSettings, ","),
            KeyBindingConfig::new(BindingAction::MoveUp, "k"),
            KeyBindingConfig::new(BindingAction::MoveUp, "<up>"),
            KeyBindingConfig::new(BindingAction::MoveDown, "j"),
            KeyBindingConfig::new(BindingAction::MoveDown, "<down>"),
            KeyBindingConfig::new(BindingAction::MoveTop, "gg"),
            KeyBindingConfig::new(BindingAction::MoveBottom, "G"),
        ],
        board_selection: vec![
            KeyBindingConfig::new(BindingAction::Quit, "q"),
            KeyBindingConfig::new(BindingAction::MoveUp, "k"),
            KeyBindingConfig::new(BindingAction::MoveUp, "<up>"),
            KeyBindingConfig::new(BindingAction::MoveDown, "j"),
            KeyBindingConfig::new(BindingAction::MoveDown, "<down>"),
            KeyBindingConfig::new(BindingAction::MoveTop, "gg"),
            KeyBindingConfig::new(BindingAction::MoveBottom, "G"),
        ],
        current_sprint: vec![
            KeyBindingConfig::new(BindingAction::Confirm, "<enter>"),
            KeyBindingConfig::new(BindingAction::MoveUp, "k"),
            KeyBindingConfig::new(BindingAction::MoveUp, "<up>"),
            KeyBindingConfig::new(BindingAction::MoveDown, "j"),
            KeyBindingConfig::new(BindingAction::MoveDown, "<down>"),
            KeyBindingConfig::new(BindingAction::MoveTop, "gg"),
            KeyBindingConfig::new(BindingAction::MoveBottom, "G"),
        ],
        profile_creation: vec![
            KeyBindingConfig::new(BindingAction::MoveUp, "k"),
            KeyBindingConfig::new(BindingAction::MoveUp, "<up>"),
            KeyBindingConfig::new(BindingAction::MoveDown, "j"),
            KeyBindingConfig::new(BindingAction::MoveDown, "<down>"),
            KeyBindingConfig::new(BindingAction::MoveLeft, "h"),
            KeyBindingConfig::new(BindingAction::MoveLeft, "<left>"),
            KeyBindingConfig::new(BindingAction::MoveRight, "l"),
            KeyBindingConfig::new(BindingAction::MoveRight, "<right>"),
            KeyBindingConfig::new(BindingAction::MoveTop, "gg"),
            KeyBindingConfig::new(BindingAction::MoveBottom, "G"),
            KeyBindingConfig::new(BindingAction::MoveLineStart, "0"),
            KeyBindingConfig::new(BindingAction::MoveLineStart, "^"),
            KeyBindingConfig::new(BindingAction::MoveLineEnd, "$"),
            KeyBindingConfig::new(BindingAction::MoveWordForward, "w"),
            KeyBindingConfig::new(BindingAction::MoveWordForward, "W"),
            KeyBindingConfig::new(BindingAction::MoveWordBackward, "b"),
            KeyBindingConfig::new(BindingAction::MoveWordBackward, "B"),
            KeyBindingConfig::new(BindingAction::MoveWordEnd, "e"),
            KeyBindingConfig::new(BindingAction::MoveWordEnd, "E"),
            KeyBindingConfig::new(BindingAction::EnterInsertBefore, "i"),
            KeyBindingConfig::new(BindingAction::EnterInsertAfter, "a"),
            KeyBindingConfig::new(BindingAction::EnterInsertLineStart, "I"),
            KeyBindingConfig::new(BindingAction::EnterInsertLineEnd, "A"),
        ],
        profiles: vec![
            KeyBindingConfig::new(BindingAction::Quit, "q"),
            KeyBindingConfig::new(BindingAction::EditProfile, "e"),
            KeyBindingConfig::new(BindingAction::DeleteProfile, "d"),
            KeyBindingConfig::new(BindingAction::NewProfile, "n"),
            KeyBindingConfig::new(BindingAction::MoveUp, "k"),
            KeyBindingConfig::new(BindingAction::MoveUp, "<up>"),
            KeyBindingConfig::new(BindingAction::MoveDown, "j"),
            KeyBindingConfig::new(BindingAction::MoveDown, "<down>"),
            KeyBindingConfig::new(BindingAction::MoveTop, "gg"),
            KeyBindingConfig::new(BindingAction::MoveBottom, "G"),
        ],
        settings: vec![
            KeyBindingConfig::new(BindingAction::Confirm, "<enter>"),
            KeyBindingConfig::new(BindingAction::MoveUp, "k"),
            KeyBindingConfig::new(BindingAction::MoveUp, "<up>"),
            KeyBindingConfig::new(BindingAction::MoveDown, "j"),
            KeyBindingConfig::new(BindingAction::MoveDown, "<down>"),
            KeyBindingConfig::new(BindingAction::MoveTop, "gg"),
            KeyBindingConfig::new(BindingAction::MoveBottom, "G"),
        ],
        my_issues: Vec::new(),
        search_issues: Vec::new(),
        conflicts: vec![
            KeyBindingConfig::new(BindingAction::MoveUp, "k"),
            KeyBindingConfig::new(BindingAction::MoveUp, "<up>"),
            KeyBindingConfig::new(BindingAction::MoveDown, "<down>"),
            KeyBindingConfig::new(BindingAction::MoveTop, "gg"),
            KeyBindingConfig::new(BindingAction::MoveBottom, "G"),
            KeyBindingConfig::new(BindingAction::ResolveConflictLocal, "l"),
            KeyBindingConfig::new(BindingAction::ResolveConflictRemote, "j"),
        ],
        sync_status: vec![
            KeyBindingConfig::new(BindingAction::SyncNow, "s"),
            KeyBindingConfig::new(BindingAction::SyncPause, "p"),
            KeyBindingConfig::new(BindingAction::SyncRetry, "t"),
            KeyBindingConfig::new(BindingAction::SyncResume, "u"),
            KeyBindingConfig::new(BindingAction::FilterAll, "A"),
            KeyBindingConfig::new(BindingAction::FilterPull, "P"),
            KeyBindingConfig::new(BindingAction::FilterPush, "U"),
        ],
        new_issue: vec![
            KeyBindingConfig::new(BindingAction::MoveUp, "k"),
            KeyBindingConfig::new(BindingAction::MoveUp, "<up>"),
            KeyBindingConfig::new(BindingAction::MoveDown, "j"),
            KeyBindingConfig::new(BindingAction::MoveDown, "<down>"),
            KeyBindingConfig::new(BindingAction::MoveLeft, "h"),
            KeyBindingConfig::new(BindingAction::MoveLeft, "<left>"),
            KeyBindingConfig::new(BindingAction::MoveRight, "l"),
            KeyBindingConfig::new(BindingAction::MoveRight, "<right>"),
            KeyBindingConfig::new(BindingAction::MoveTop, "gg"),
            KeyBindingConfig::new(BindingAction::MoveBottom, "G"),
            KeyBindingConfig::new(BindingAction::MoveLineStart, "0"),
            KeyBindingConfig::new(BindingAction::MoveLineStart, "^"),
            KeyBindingConfig::new(BindingAction::MoveLineEnd, "$"),
            KeyBindingConfig::new(BindingAction::MoveWordForward, "w"),
            KeyBindingConfig::new(BindingAction::MoveWordForward, "W"),
            KeyBindingConfig::new(BindingAction::MoveWordBackward, "b"),
            KeyBindingConfig::new(BindingAction::MoveWordBackward, "B"),
            KeyBindingConfig::new(BindingAction::MoveWordEnd, "e"),
            KeyBindingConfig::new(BindingAction::MoveWordEnd, "E"),
            KeyBindingConfig::new(BindingAction::EnterInsertBefore, "i"),
            KeyBindingConfig::new(BindingAction::EnterInsertAfter, "a"),
            KeyBindingConfig::new(BindingAction::EnterInsertLineStart, "I"),
            KeyBindingConfig::new(BindingAction::EnterInsertLineEnd, "A"),
            KeyBindingConfig::new(BindingAction::Confirm, "<enter>"),
        ],
    }
}
