use crate::ui::interaction::ActionId;

pub(super) fn action_description(action: ActionId) -> Option<&'static str> {
    match action {
        ActionId::Quit => Some("Quit"),
        ActionId::Refresh => Some("Refresh"),
        ActionId::Confirm => Some("Confirm"),
        ActionId::GoHome => Some("Home"),
        ActionId::OpenCurrentSprint => Some("Current sprint"),
        ActionId::OpenMyIssues => Some("My issues"),
        ActionId::OpenSearchIssues => Some("Search issues"),
        ActionId::OpenNewIssue => Some("New issue"),
        ActionId::OpenProfiles => Some("Profiles"),
        ActionId::OpenBoards => Some("Boards"),
        ActionId::OpenSettings => Some("Settings"),
        ActionId::OpenSyncStatus => Some("Sync status"),
        ActionId::ResolveConflictLocal => Some("Use local"),
        ActionId::ResolveConflictRemote => Some("Use Jira"),
        ActionId::SyncNow => Some("Sync now"),
        ActionId::SyncPause => Some("Pause"),
        ActionId::SyncRetry => Some("Retry"),
        ActionId::SyncResume => Some("Resume"),
        ActionId::FilterAll => Some("Filter all"),
        ActionId::FilterPull => Some("Filter pull"),
        ActionId::FilterPush => Some("Filter push"),
        ActionId::NewProfile => Some("New profile"),
        ActionId::EditProfile => Some("Edit profile"),
        ActionId::DeleteProfile => Some("Delete profile"),
        ActionId::OpenInBrowser => Some("Open in browser"),
        ActionId::EditIssue => Some("edit issue"),
        ActionId::TransitionIssue => Some("transition issue"),
        ActionId::AddComment => Some("add comment"),
        ActionId::AssignToMe => Some("assign to me"),
        ActionId::FocusQuery => Some("edit query"),
        ActionId::PageUp => Some("page up"),
        ActionId::PageDown => Some("page down"),
        ActionId::MoveUp => Some("Up"),
        ActionId::MoveDown => Some("Down"),
        ActionId::MoveLeft => Some("Left"),
        ActionId::MoveRight => Some("Right"),
        ActionId::MoveTop => Some("Top"),
        ActionId::MoveBottom => Some("Bottom"),
        ActionId::MoveLineStart => Some("Line start"),
        ActionId::MoveLineEnd => Some("Line end"),
        ActionId::MoveWordForward => Some("Word forward"),
        ActionId::MoveWordBackward => Some("Word back"),
        ActionId::MoveWordEnd => Some("Word end"),
        ActionId::EnterInsert(_) => Some("Insert"),
        ActionId::RawInput(_) => None,
    }
}
